updated to Laravel Auditing version 7
betapeak/laravel-auditing-filesystem pull request #1
Opened 2018-07-19 15:21 UTC by zack-hable

Removed support from Version 4 and switched to Version 7 (latest).  I'm not sure if the versions between would be supported (5-6).

2018-07-20 11:02 UTC, ymslavov requested changes

2018-07-20 11:02 UTC, ymslavov commented on README.md
> +More information on using customer drivers with owen-it/laravel-auditing can be found on their [homepage](http://www.laravel-auditing.com/docs/7.0/audit-drivers)
I believe correct wording is "Community drivers"

2018-07-20 11:02 UTC, ymslavov commented
@zack-hable Thank you for your PR! There's just a minor wording tweak and I'll merge it in.

2018-07-20 18:06 UTC, zack-hable commented
Awesome!  I have fixed that typo in the readme.

2018-07-27 14:33 UTC, zack-hable commented
@ymslavov Are there any other issues?

2018-07-28 19:53 UTC, merged

2018-07-28 19:59 UTC, ymslavov commented
Thank you for the contribution and sorry for the delay @zack-hable